spring.application.name=ClinicManager

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/clinicdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Admin123}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.liquibase.change-log=db/db-master.xml
spring.liquibase.enabled=true


logging.level.org.springframework.boot=INFO
logging.level.org.apache.catalina=INFO

server.error.include-stacktrace=never
logging.level.root=INFO


app.jwtSecret=${JWT_SECRET:random-string}
app.jwtExpirationMs=18000000
app.corsAllowedOrigins=${CORS_ALLOWED_ORIGINS:http://localhost:5173}

spring.data.redis.host=${SPRING_REDIS_HOST:localhost}
spring.data.redis.port=6379
